services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./data/db:/data
    env_file:
      - ./.env
    depends_on:
        - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
